# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: AutoRun

on:
  schedule:
  - cron: "0 11,12,13,14,15 * * *"

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install leaps package
        run: Rscript -e 'install.packages("leaps", dependencies = TRUE)'
      - name: Install skimr package
        run: Rscript -e 'install.packages("skimr", dependencies = TRUE)'
      - name: Install ggplot2 package
        run: Rscript -e 'install.packages("ggplot2", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install stopwords package
        run: Rscript -e 'install.packages("stopwords", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript Test_ScrapingData.R
